### ISSUE TITLE
Driver MySQL is not installed

### ISSUE THREAD

**Issue by wonboyn** [mtxr/vscode-sqltools#840] opened 2021-07-15 06:53 UTC
I am using VS Code remote containers and have installed the SQLTools plugin (v0.23.0) and the SQLTools MySQL/MariaDB plugin (v0.2.0) into the container (not the local VS Code instance).

This has been working fine for a while but in the last day I have started getting the following error when trying to connect to the database: Driver MySQL is not installed

1. Setup a remote container definition (devcontainer.json) that installs SQLTools & SQLTools MySQL plugins & a database connection
2. When the container has started attempt to connect to the database

**Expected behavior**
Connection to MySQL database works

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.58.1
 - OS: Mac
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL v5.7

**Comment by gjsjohnmurray** [comment] 2022-09-05 03:55
Maybe a duplicate of #906

**Comment by gjsjohnmurray** [comment] 2022-09-05 03:57
Closing as duplicate. @wonboyn if you disagree please reopen it.

**Closed as completed by gjsjohnmurray** 2022-09-05 03:57 UTC
Labels: duplicate, mysql
