### ISSUE TITLE
Path to sqlite database must be absolute

### ISSUE THREAD

**Issue by kjjohnsen** [mtxr/vscode-sqltools#762] opened 2021-02-02 11:45 UTC
**Describe the bug**
The default path when selecting a database file is relative to the project folder, e.g. ${workspaceFolder:test}/test.db .  SQLTools will connect to the database, but won't show any tables or allow queries.  If you change the path in settings to be absolute, e.g. c:/test.tb, it will work. 

**To Reproduce**
1. Put database file in project folder
2. Click on "Add new connection"
3. Connect
4. See that there are no tables

**Expected behavior**
That the tables would show without the above hack.

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.52.1
 - OS: Windows
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [x ] SQLite
   - [ ] Other? Which...
 - Database version: sqlite3

**Comment by liudonghua123** [comment] 2021-03-03 04:12
I have the same problem. I can't make it work even I changed to the absolute path in `setttings.json` sometimes. I always got no such table error. I think the database file connected should be shown in the opened windows or the log window for debugging.

**Comment by mtxr** [comment] 2021-03-22 01:38
Can you open a PR for this?

**Comment by JourdanClark** [comment] 2021-07-21 02:59
There is more to this. After simply doing "Test Connection" on the file, it will tell me that the connection is good and it will create a directory at "C:/c%3A". It is URL encoding the file path. It is creating a new empty database when it does this.

EDIT:

For clarification, the original path of 
`C:\Users\School\Documents\Projects\Unit 3 - Data Engineering\Sprint 10 - SQL and Databases\Module 1 - Introduction to SQL\rpg_db.sqlite3`

becomes
`C:\c%3A\Users\School\Documents\Projects\Unit%203%20-%20Data%20Engineering\Sprint%2010%20-%20SQL%20and%20Databases\Module%201%20-%20Introduction%20to%20SQL\rpg_db.sqlite3`

Setting it to an absolute path in the settings.json fixed this.

```json
// settings.json
{
    "sqltools.connections": [
        {
            "previewLimit": 50,
            "driver": "SQLite",
            "database": "C:\\Users\\School\\Documents\\Projects\\Unit 3 - Data Engineering\\Sprint 10 - SQL and Databases\\Module 1 - Introduction to SQL\\rpg_db.sqlite3",
            "name": "rpg_db"
        }
    ],
    "sqltools.useNodeRuntime": true
}
```

**Comment by flatrick** [comment] 2022-06-24 22:06
just wanted to chime in that I'm having the same issue in case it could be of any help, and I also get the file created at `C:\c%3A\my\local\path\dbfilename`, which should point to some bug while converting the pathway into a string.

@mtxr curious question, why did you want a PR created by the bug-reporter? Correct me if I'm totally wrong here, but I would only create a PR if I had a possible solution created already.

**Comment by gjsjohnmurray** [comment] 2022-07-23 00:43
Duplicate of #703

**Closed by gjsjohnmurray** 2022-07-23 00:43 UTC
Labels: triage, sqlite
