### ISSUE TITLE
blocks with trailing comments fail with "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by brocla** [mtxr/vscode-sqltools#1029] opened 2022-11-05 21:12 UTC
**Describe the bug**
Blocks of SQL code that are followed with C-style comments /*...*/ fail with error **Cannot read properties of undefined**

**To Reproduce**
```
-- @block
select * FROM Student;
/* trailing comment */
```
**Expected behavior**
Should have shown all the contents of table `Student`.

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.25.1]
 - VS Code Version: [e.g 1.73.0]
 - OS: [e.g. Linux (Ubuntu)]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [Ver 8.0.31-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))]

**Comment by gjsjohnmurray** [comment] 2023-04-27 15:12
Duplicate of #1131

**Closed as completed by gjsjohnmurray** 2023-04-27 15:12 UTC
Labels: duplicate, mysql
