### ISSUE TITLE
Use single Tab

### ISSUE THREAD

**Issue by firedev** [mtxr/vscode-sqltools#800] opened 2021-04-26 11:21 UTC
**Is your feature request related to a problem? Please describe.**

Is it possible to use single tab for output? I am trying to have like SQL notebook - edit markdown document, write query, execute write down results and forget about it. But after a while SQL tools tabs eat up all memory and it hangs, have to close it manually.

**Describe the solution you'd like**

I would like to just mash `Cmd-E-E` until I get what I want

**Describe alternatives you've considered**

DataGrip for instance, keeps only one tab for results

**Additional context**

![image](https://user-images.githubusercontent.com/115612/116074617-acd8dd00-a69a-11eb-82a0-4fde14b5b16c.png)

**Comment by binhtddev** [comment] 2021-11-22 08:45
Duplicate of #632

**Comment by gjsjohnmurray** [comment] 2022-04-22 08:03
Closing as duplicate.

**Closed as completed by gjsjohnmurray** 2022-04-22 08:03 UTC
Labels: duplicate, feature request
