### ISSUE TITLE
Can't add new connection

### ISSUE THREAD

**Issue by alexey-rio** [mtxr/vscode-sqltools#655] opened 2020-07-14 23:42 UTC
Hi guys,

I've installed SQLTools extension for VS Code and when I am trying to add new connection - nothing happens. 
I can't see any errors popping up. 
Hence I've been unable to add a new connection to a DB.

Connection assistant is not being displayed.

VS Code version: 1.47.1 (system setup)
SQLTools version: 0.22.10
OS: Windows 10 1809

**Comment by rimutaka** [comment] 2020-07-15 01:09
While this problem is being looked into you can add a new connection manually to `sqltools.connections` in `settings.json` as described in https://vscode-sqltools.mteixeira.dev/driver/postgresql.

It probably won't take you far, though. Running queries returns a blank SQLTools Results pane. Looks like something's seriously broken ...

**Comment by LuisEmilioJuarez** [comment] 2020-07-15 23:53
got this problem too please if you could look up into it thanks a lot 
![image](https://user-images.githubusercontent.com/61983679/87610977-1a93b980-c6c4-11ea-9702-0fcb6c8018ff.png)

**Comment by hriziya** [comment] 2020-07-16 14:13
I am facing the same problem. may be something is broken in the latest version?

**Comment by hriziya** [comment] 2020-07-16 14:24
I have added connection manually by modifying the `sqltools.connections` in `settings.json` and then again I can not see the query result.

![image](https://user-images.githubusercontent.com/4135216/87682968-19cf5600-c79e-11ea-9292-16e001e89dea.png)

**Comment by jimrandell** [comment] 2020-07-17 08:07
Same with me (I hope this can be resolved, this is my fav SQLtool
 

- SQLTools
  - Version: v0.22.10

- VS Code 
  - Version: 1.47.1 (user setup)
  - Commit: 485c41f9460bdb830c4da12c102daff275415b53
  - Date: 2020-07-13T22:42:53.386Z
  - Electron: 7.3.2
  - Chrome: 78.0.3904.130
  - Node.js: 12.8.1
  - V8: 7.8.279.23-electron.0
  - OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/3543506/87763539-dcee7800-c80c-11ea-982b-b471620077a0.png)

**Comment by gabrielcardoso30** [comment] 2020-07-17 19:42
Ótima tarde a todos! Eu também estou com o mesmo problema... :(

![image](https://user-images.githubusercontent.com/57575695/87824836-6a9d8800-c84c-11ea-8d04-ab81f4abea8e.png)

**Comment by gabrielcardoso30** [comment] 2020-07-17 19:49
Fiz um downgrade de versão, resolveu, agora consigo usar :D 
Coloquei na versão 0.22.9

**Comment by wscatao** [comment] 2020-07-20 19:21
Mesmo problema aqui? Como fez o downgrade @gabrielcardoso30 ?

**Comment by bRaInT00T** [comment] 2020-07-22 15:28
Duplicate of #639

**Comment by mtxr** [comment] 2020-07-24 02:32
Fixed on v0.22.11.

**Comment by EugZol** [comment] 2021-01-27 00:06
Same error in 0.23.0.

**Comment by Chimecrypto** [comment] 2021-04-03 19:42
Unfortunately, No one has the answer to this problem...

**Comment by AngelinCalu** [comment] 2021-06-04 13:11
This still seems to be an issue on the current version.

**Comment by MarcelSchuermann** [comment] 2021-07-09 15:01
> This still seems to be an issue on the current version.

Agree, the error still exists. 
Any solutions / workarounds?

**Comment by Chimecrypto** [comment] 2021-07-12 08:15
None. i failed my assignment for not resolving this.

**Comment by pau1tuck** [comment] 2021-08-13 14:20
This is still a problem. 
`Running the contributed command: 'sqltools.addConnection' failed.` (mariadb on Arch Linux)

**Comment by malocan** [comment] 2021-09-10 13:37
<img width="1635" alt="Снимок экрана 2021-09-10 в 16 34 24" src="https://user-images.githubusercontent.com/49976288/132861851-8aa86064-cc16-4770-b4eb-8a89a042fb29.png">
 The same issue. Still can not go to the next step of creating new connection

**Comment by aecliam** [comment] 2021-10-01 08:35
same issue with me too. I've been trying to disable and enable like what others have said but it's still an error.

**Comment by VolpiGiuliano** [comment] 2022-08-04 11:59
Same issue, and it always shows this message
<img width="932" alt="Screenshot 2022-08-04 135902" src="https://user-images.githubusercontent.com/69405583/182841807-479003b5-9e84-45c5-bda6-d555f928cc15.png">

**Comment by gjsjohnmurray** [comment] 2022-08-04 16:16
@RagionierBolo yours looks more like #668

**Comment by seeejj** [comment] 2022-10-05 03:32
I'm also facing this issue today in 2022. Any luck?

**Comment by gjsjohnmurray** [comment] 2022-10-05 06:18
@seeejj did you try the suggestion at https://github.com/mtxr/vscode-sqltools/issues/668#issuecomment-993403972 to delete one instance of a duplicate connection definition?

**Comment by Eruasa** [comment] 2022-11-14 10:54
> @seeejj did you try the suggestion at [#668 (comment)](https://github.com/mtxr/vscode-sqltools/issues/668#issuecomment-993403972) to delete one instance of a duplicate connection definition?

Doesn't sadly work if you don't have any connections at all.
And I don't know how I can manually add a connection, since I have trouble understanding the syntax.

_EDIT_
Just restarted VSCode, and now it works, no idea what changed, but I did restart it before like every time after I install an extension,

**Comment by seeejj** [comment] 2022-11-22 00:52
@gjsjohnmurray Same thing to @Eruasa happened with me. Had restarted repeatedly when I was actively trying to fix it, it didn't work, and one day it did again.

I pretty much gave up trying to get VSCode to work, and didn't use SQLTools for a couple of weeks. Then one day, after many VSCode restarts since the day I had this issue, it suddenly worked again.

**Comment by Vilgot-thy** [comment] 2022-12-02 07:28
Hi.
Have the same problem but I'm geting this error
![image](https://user-images.githubusercontent.com/92026267/205238761-48f22b97-010f-4033-97c7-3d90a730beec.png)

**Comment by gjsjohnmurray** [comment] 2022-12-02 07:54
@Vilgot-thy does the problem still happen after a complete reboot of the workstation? Perhaps https://github.com/microsoft/vscode/issues/125993

**Comment by Vilgot-thy** [comment] 2022-12-02 07:57
Yes that did fix the error, but I stile only get this
![image](https://user-images.githubusercontent.com/92026267/205244036-b80bf720-7827-42ac-9d44-3ed704e2e767.png)

edit:
seems to work now thanks you for the help

**Comment by gjsjohnmurray** [comment] 2023-01-06 15:45
Starting with today's 0.27.1 release it should no longer be possible to define connections with duplicate IDs using the UI.

**Closed by gjsjohnmurray** 2023-01-06 15:45 UTC
Labels: triage

**Comment by smm-h** [comment] 2023-03-25 20:05
You guys should check out this thread on SO:

https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

The top answer worked for me.

**Comment by carolinaqvargas** [comment] 2023-04-27 08:29
![Screenshot 2023-04-27 102303](https://user-images.githubusercontent.com/21103877/234804606-016570e9-ff39-497d-8deb-446df59a7fe8.jpg)
Hi everyone, could you please help me with this issue? 
Successful connections won't appear on the side bar. Even after I click 'connect now'
Thank you!

**Comment by gjsjohnmurray** [comment] 2023-05-04 10:57
@carolinaqvargas from Command Palette (F1) please run `Preferences: Open User Settings (JSON)` and review the `sqltools.connections` object. Are there any duplicate `name`s?

Temporarily disable the object by renaming it, e.g. to `Xsqltools.connections`. Save the change, then restart VS Code. Define a new connection, testing it when prompted. Does the tree now show this entry?
