### ISSUE TITLE
Tree view support (PGSQL)

### ISSUE THREAD

**Issue by mfulton26** [mtxr/vscode-sqltools#473] opened 2020-01-02 16:51 UTC
I see that I'm supposed to get a tree to explore database objects but I'm not seeing anything even after I've successfully connected to the database.

I didn't see a good place to ask questions so I'm opening an issue instead.

Please advise.

Expected

![image](https://user-images.githubusercontent.com/5588957/71679361-03efcb80-2d4d-11ea-8cd5-3dd15d7edbae.png)

Actual

![image](https://user-images.githubusercontent.com/5588957/71679682-bfb0fb00-2d4d-11ea-9864-548b43a642bb.png)

**Comment by mtxr** [comment] 2020-01-03 23:32
Thanks @mfulton26 

this is probably caused by #472 .
it's obvious we had a problem connecting, it's just not showing. 

Closing.

**Closed by mtxr** 2020-01-03 23:32 UTC
Labels: triage
