### ISSUE TITLE
Does the extension provide linting functionalities?

### ISSUE THREAD

**Issue by simplemind** [mtxr/vscode-sqltools#974] opened 2022-09-16 12:22 UTC
Hi,
Could you please let me know if the extension has the functionality to highlight errors in SQL code? I could not find an answer within the list of features.
I code in MySQL and I have installed MySQL driver. SQLTools does not prompt any errors and I would like to know if this is because it is not designed to lint SQL code. Or because there is something missing on my end.
Thank you
Karolis

**Comment by gjsjohnmurray** [comment] 2022-09-16 13:54
No, the extension doesn't yet leverage any of the [Diagnostic](https://code.visualstudio.com/api/references/vscode-api#Diagnostic)-related parts of the VS Code API, which is how extensions contribute to the Problems view, nor [CodeAction](https://code.visualstudio.com/api/references/vscode-api#CodeAction)s which linters typically use to offer fixes.

Interesting idea though...

**Comment by simplemind** [comment] 2022-09-16 15:54
Thank you for a quick reply. Good to know its an idea worth considering

**Comment by mtxr** [comment] 2022-09-17 11:51
possibly duplicate of #943

**Comment by gjsjohnmurray** [comment] 2022-09-17 13:19
@mtxr I agree. Tagged as duplicate and closed.

**Closed as completed by gjsjohnmurray** 2022-09-17 13:19 UTC
Labels: duplicate, feature request
