### ISSUE TITLE
Cannot run function/procedure definition

### ISSUE THREAD

**Issue by abdelhaqelamraoui** [mtxr/vscode-sqltools#1220] opened 2023-10-01 14:37 UTC
**Describe the bug**
The extension cannot run definitions of functions and procedures.
For example, with the simple function:
`
DELIMITER  $$
CREATE FUNCTION test()
    returns INT
    deterministic
    BEGIN
       RETURN 1;
    END $$
DELIMITER ;
`
It  returns the following error:
_You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER  $$_

**Expected behavior**
No errors.

**Screenshots**
![image](https://github.com/mtxr/vscode-sqltools/assets/77709772/50a4688d-65f0-4227-99dd-9084a3805d93)

**Desktop (please complete the following information):**
 - SQLTools Version:  v0.6.0
 - VS Code Version: 1.82.2
 - OS: Linux
 - Driver:
   - [x] MySQL/MariaDB

 - Database version: mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper

**Comment by gjsjohnmurray** [comment] 2023-11-02 12:42
Duplicate of #529

**Closed as completed by gjsjohnmurray** 2023-11-02 12:42 UTC
Labels: duplicate, mysql
