### ISSUE TITLE
publishing sqltools in Open VSX Registry "managed by Eclipse Foundation"

### ISSUE THREAD

**Issue by Hesham937** [mtxr/vscode-sqltools#749] opened 2020-12-18 00:20 UTC
could you please consider in the future publish you extension in open VFX 

open VFX is an open source alternative to vscode marketplace

open VFX homepage and github page : 

https://open-vsx.org/

https://github.com/eclipse/openvsx

thanks

**Comment by protron** [comment] 2020-12-26 23:56
This issue seems like a duplicate of #697 

I'm pointing it out in order for people to vote (thumbs up) on that original issue.
That one already has nice description, some thumbs up and some comments.

**Comment by mtxr** [comment] 2021-03-23 05:37
Duplicate of #697. Closing

**Closed by mtxr** 2021-03-23 05:37 UTC
Labels: feature request
