### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client

### ISSUE THREAD

**Issue by nmggithub** [mtxr/vscode-sqltools#246] opened 2019-05-23 23:33 UTC
I am in college, and my University has given us each a MariaDB database login for a database course we have. PHPMyAdmin can connect, as well as the Linux mariadb package, and also the Node.js mariadb package. This extension does not work and gives the above error. I have tried the known fix and it did not solve it.

**Comment by nmggithub** [comment] 2019-05-23 23:38
Update: it appears my user is: "IDENTIFIED VIA pam". Not sure if this is what is causing the auth failure.

**Comment by mtxr** [comment] 2019-05-23 23:57
Witch MariaDB version are you using?

Also, can you try to connect using 'xprotocol' as described in https://vscode-sqltools.mteixeira.dev/connections/mysql#know-errors-and-how-to-fix

**Comment by mtxr** [comment] 2019-05-24 12:35
@nmggithub did you get it working?

I'll close this issue, but please, re-open if you still face some problems.

**Comment by nmggithub** [comment] 2019-05-24 13:24
It is MariaDB v10.1.32. And, per my last message, "I have tried the known fix and it did not solve it." So, yes I did try the xprotocol fix. It did not solve it.

**Comment by nmggithub** [comment] 2019-05-24 13:57
After looking into it some more, it appears the issue is with the `mysql` Node.js package. I just installed it locally and am receiving the same error. I do not receive the error when using the `mariadb` Node.js package. There is an [open issue](https://github.com/mysqljs/mysql/issues/2001) over at the repository for the `mysql` package and I informed them of this. I can look through the source code of both packages and see if I can find what the issue is.

**Comment by mtxr** [comment] 2019-05-24 13:58
Which port are you using? Did you try adding a 0 in the end? Eg: 3306 -> 33060

MySQL/MariaDB xprotocol usually runs in another port.

Would you mind sharing your connection settings? blurring username, password and server of course.

I'll try to reproduce this here during the weekend.

**Comment by mtxr** [comment] 2019-05-24 13:59
> After looking into it some more, it appears the issue is with the `mysql` Node.js package. I just installed it locally and am receiving the same error. I do not receive the error when using the `mariadb` Node.js package. There is an [open issue](https://github.com/mysqljs/mysql/issues/2001) over at the repository for the `mysql` package and I informed them of this. I can look through the source code of both packages and see if I can find what the issue is.

That's awesome! If you want, you can submit a PR implementing a dialect for MariaDB only. Then we could detach the support from mysql to mariadb.

Take a look at #219

**Comment by nmggithub** [comment] 2019-05-24 14:03
> > After looking into it some more, it appears the issue is with the `mysql` Node.js package. I just installed it locally and am receiving the same error. I do not receive the error when using the `mariadb` Node.js package. There is an [open issue](https://github.com/mysqljs/mysql/issues/2001) over at the repository for the `mysql` package and I informed them of this. I can look through the source code of both packages and see if I can find what the issue is.
> 
> That's awesome! If you want, you can submit a PR implementing a dialect for MariaDB only. Then we could detach the support from mysql to mariadb.
> 
> Take a look at #219 , let me know what you think

I can definitely give that a look. I'm not sure when I will be able to fully do it as I am busy with college work. However, I will look into it.

**Comment by nmggithub** [comment] 2019-05-30 04:17
OK, I am not sure if you noticed, but I am currently in the process of working put a pull request over at the mysqljs repository. Once done there, I can then make a pull request to this repository to add an option in the New Connection dialog, which will allow it to use the new featured added.

**Comment by mtxr** [comment] 2019-05-30 04:24
Nice @nmggithub !

No hush. Let's do it in your time.

**Comment by mtxr** [comment] 2019-08-10 04:04
@nmggithub any updates on the mysqljs issue?

**Comment by nmggithub** [comment] 2019-08-10 22:42
Hey, so sorry. I've been busy and this issue was largely in regards to connecting to the database set up by my school. I have since finished the course, so I don't really necessarily need this issue to be fixed for me personally.

**Comment by mtxr** [comment] 2019-08-11 05:00
Thanks for the update @nmggithub. I'll close this since the aforementioned possible solutions works for most of the cases.

If this come up again in the future, we can work on this, but now I'll prioritize some other issues.

**Closed by mtxr** 2019-08-11 05:00 UTC
Labels: bug, good first issue

**Comment by govindasharma1986** [comment] 2021-07-19 22:38
Hi @mtxr,

Just now I too faced this issue. Here's a snippet for it:
```
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

I was trying to connect to our prod mysql server and that's when I faced it. I am able to connect to it from python mysql.connector, sqlalchemy and mysql workbench.

I wished to able to connect to it from vscode for productivity.

I read that instead of mysql package if we use mysql2 then that would solve the issue. I am not in JS so not sure about the fix. Whenever you find time, can you pls look into it?

Thanks

**Comment by govindasharma1986** [comment] 2021-07-22 20:14
Hi @mtxr ,

Can we reopen the issue and prioritize it?

Thanks

**Comment by PvdBerg1998** [comment] 2021-08-13 11:32
Same issue for me

**Comment by scdigitalmedia** [comment] 2021-11-15 22:37
Having the same issue. I've tried the altering user and making updates to the mysql conf file, to no avail. Any other ideas?

**Comment by zachary-wang12** [comment] 2023-02-08 15:35
Same issue.

> Sysinfo

|item|version|
|---|---|
|System|Windows 11 Professional 22H2|
|mysql | 8.0.32|
|vscode|1.75.0|
|SQLTools|v0.27.1|
|SQLTools MySQL/MariaDB|v0.5.1|

> Settings in SQLTools:

![image](https://user-images.githubusercontent.com/33516065/217575147-c887b9a7-107c-47f2-a9a5-8149ae85364c.png)


> Log from SQLTools:
```log
[1675868679377] INFO  (ext): EXECUTING COMMAND => sqltools.selectConnection
[1675868679377] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1675868679377] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1675868679380] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1675868679380] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1675868679381] INFO  (ls): REQUEST RECEIVED => connection/ConnectRequest
[1675868679381] INFO  (ls): Connection instance created for testdb.
    ns: "conn-manager"
[1675868679382] ERROR (ls): {"code":-1,"data":{"driver":"MySQL","driverOptions":{"mysqlOptions":{"authProtocol":"default"}}},"name":"Error"}
    ns: "conn"
[1675868679382] ERROR (ls): Connecting error: {"code":-1,"data":{"driver":"MySQL","driverOptions":{"mysqlOptions":{"authProtocol":"default"}}},"name":"Error"}
    ns: "conn-manager"
[1675868679382] ERROR (ls): Open connection error
    ns: "conn-manager"
[1675868679383] ERROR (ext): ERROR: Error opening connection ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client, {"code":-1,"data":{"driver":"MySQL","driverOptions":{"mysqlOptions":{"authProtocol":"default"}}}}
    ns: "error-handler"
```

**Comment by zachary-wang12** [comment] 2023-02-08 15:55
@nmggithub @govindasharma1986 @PvdBerg1998 

I don't know if my issue same as yours. 

But mine has solved, with following https://github.com/mtxr/vscode-sqltools/issues/1095#issuecomment-1399206049, and changed the `port` to 33060,  `authProtocol` to xprotocol and add `connectionTimeout` as 15 (I think any integer may be valid)

> Config in SQLTools

![image](https://user-images.githubusercontent.com/33516065/217580551-6ab29b06-21cb-4a03-a97a-f73c0aa6f818.png)
