### ISSUE TITLE
MySQL/MariaDB Error: Cannot destructure property 'name' of 'undefined' as it is undefined

### ISSUE THREAD

**Issue by incansvl** [mtxr/vscode-sqltools#723] opened 2020-10-28 15:24 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/mtxr/vscode-sqltools/issues/723)

OS: Windows 10 Pro 64 bit
MariaDB: 10.3.12
VSCode: 1.50.1
SQLTools: 0.23.0
SQLTools MySQL/MariaDB: 0.2.0

**Description**
A ~250 line (with comments) SQL script was working correctly in both the MySQL console (mysql command) and in SQLTools (SQLT).

I then added a simple "print status" type command in the script, of the form-

```
SELECT CONCAT(
	'Output written to: ', @OutputDirectory, @FileName
)  AS  '';
```

Originally I had a syntax error, so the script was failing in both environments, but having fixed the error, the script runs ok in the console but continues to fail when run from VSCode with the error:

`Cannot destructure property 'name' of 'undefined' as it is undefined`

Note: If I try to copy+paste the text of the console error into this bug report the result is: `[object Object]` not sure if that is significant?

**To Reproduce**
(see attachment)

**Expected behavior**
Script runs and writes the text to the console:

```
+-------------------------------------------------------------------------------------+
|                                                                                     |
+-------------------------------------------------------------------------------------+
| Output written to: C:/Windows/Temp/der2_cciRefset_RefsetDescriptorDelta_GB_20201024 |
+-------------------------------------------------------------------------------------+
```

[VSTools test case.sql.txt](https://github.com/mtxr/vscode-sqltools/files/5452924/VSTools.test.case.sql.txt)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars.githubusercontent.com/u/90935462?v=4' alt='michaelweissdm' width=24 height=24> michaelweissdm](https://issuehunt.io/u/michaelweissdm) ($10.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/mtxr/vscode-sqltools/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by OzzyTheGiant** [comment] 2020-11-04 21:34
I second this error. The code I'm running on MySQL 8.0 is just three simple UPDATE statements:

```SQL
UPDATE Employees SET RoleID = 1 WHERE Role = 'administrator';
UPDATE Employees SET RoleID = 2 WHERE Role = 'receptionist';
UPDATE Employees SET RoleID = 3 WHERE Role = 'staff';
```

**Comment by NullsByte** [comment] 2020-12-05 02:55
I'm getting this error all the time now.  I'll have to switch over to mySQL workbench in the mean time.
Running MariaDB 10.3.25.
Latest VSCode version: 1.51.1.
SQLTools version: 0.23.0.

`DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(12) NOT NULL,
    userpass VARCHAR(12) NOT NULL,
    email VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE
);`

**Comment by SKJoy** [comment] 2020-12-15 17:35
Executing SQL results into this error! Opening records from explorer works fine.

**Comment by rafaelurben** [comment] 2021-01-28 17:25
Same error here. But this error only occured when using create or drop statements, not for select. (I haven't tested it with other statements)

**Comment by designermonkey** [comment] 2021-04-15 11:25
Any updates regarding this error?

**Comment by LordDewi** [comment] 2021-05-29 04:48
Something that I just discovered...SQLTools does not seem to like Commenting. I've been watching this tutorial which introduced me to SQLTools and it works fine in the tutorial but did not for me. https://www.youtube.com/watch?v=Cz3WcZLRaWc
What I was doing however was commenting out the previous tests, to save them so I could go back and look at them later. Then I would put the new code ABOVE the commented text, assuming it would ignore everything that was commented out.

Apparently NOT. When I moved the NEW code underneath the commented out code it worked with out the error we are all experiencing. See my code below.

Interestingly, because I was so familiar with using PHP and MySQL and using PHPMyAdmin to check things I found that even with some of those errors, like the INSERT INTO, it still did do the INSERT, even with the error. (I checked PHPMyAdmin).

So this might help some of you, although it is still a bug, all comments should be ignored. Most of you just post the code that is failing but not your full code do I don't know if you have comments before your code.

If I put the SELECT * right under the -- @BLOCK it fails.

I hope this helps some of you.

UPDATE: (A Few minutes later) - I used the code block but it didn't appear as code so attached is a pic of my code.
![vscodesqltools](https://user-images.githubusercontent.com/8094089/120058345-036d6a00-bfff-11eb-90cf-83cd667af471.png)


`-- @BLOCK
-- CREATE TABLE Users(
--     id INT PRIMARY KEY AUTO_INCREMENT,
--     email VARCHAR(255) NOT NULL UNIQUE,
--     bio TEXT,
--     country VARCHAR(2CREATE TABLE Users(
--         id INT PRIMARY KEY AUTO_INCREMENT,
--         email VARCHAR(255) NOT NULL UNIQUE,
--         bio TEXT,
--         country VARCHAR(2)
--     );)
-- );
-- SELECT * FROM Users; 
-- INSERT INTO Users (email, bio, country) 
-- VALUES
--     ('hellow2@world.com', 'foo', 'MX'),
--     ('dewi1@lorddewi.com', 'Dewi', 'US'),
--     ('david1@daviddevaneyjr.com', 'David', 'US');
SELECT * FROM Users; `

**Comment by rafaelurben** [comment] 2021-05-29 13:30
Yeah, that could really be the problem - I remember also using comments when the issue occurred.

@LordDewi This is not directly related to this topic, but the reason your code block didn't work is that you only used one backtick (``` ` ```), which corresponds to an inline code block. For multiline code blocks, you should use three backticks (` ``` `).
You can find more information [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). ;)

**Comment by grantwforsythe** [comment] 2021-06-10 21:04
I ran into this same issue when trying to change the schema of a table with `ALTER TABLE`.

```sql
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE person
MODIFY person_id SMALLINT UNSIGNED AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1
```

I ended up just running these commands in the Workbench and switch back to `SQLTools` afterwards. As of yet, I haven't run into any other instances of this issue.

#### To Reproduce 
Follow pages `17` to `34` from [Learning SQL](https://www.amazon.com/Learning-SQL-Generate-Manipulate-Retrieve/dp/1492057614/ref=sr_1_1?dchild=1&keywords=learning+sql&qid=1623358580&sr=8-1).

**Comment by zdravkoggeorgiev** [comment] 2021-07-30 07:40
This error occurred to me when I try to execute CREATE TABLE statements. The interesting part is, that table was CREATED. So SQL executed successfully. I think it's a problem with display of results.

**Comment by nvmker** [comment] 2021-09-16 19:54
I tried to run multiple INSERT queries and got the same error.

**Comment by michaelweissDM** [comment] 2021-10-20 22:57
Really enjoy SQL tools in vs-code.  Just running basic select statements with 1 join and a where/ group by and the only way not to get the error: 
Cannot destructor property 'name' of 'undefined' as it is undefined
Is to take the comments out.  Not to bad on small queries but with my longer complex queries and procedures I have to comment through out the script.   Going to send a small donation and prayer this gets resolved cause I love the platform and the extension.

**Comment by mike-pt** [comment] 2021-11-04 17:59
I'm seeing the same in any insert query, they are indeed successful, initially I though something was wrong with the queries, but I guess its with the output of the result.

**Comment by SiJiL82** [comment] 2021-12-22 11:06
Getting the same thing with literally just the SQL below, no comments.

USE testdb;
SHOW TABLES;

Strangely, SHOW DATABASES; works fine though.

**Comment by rconjoe** [comment] 2022-01-06 15:37
Same issues here. Flatpak VSCode on Ubuntu 21.10.

All of my queries worked fine until I ran an INSERT; with other blocks commented out. After that, even queries that worked before are throwing the `Cannot destructure property 'name'` error.

**Comment by FrankCoder** [comment] 2022-05-21 13:55
This is still an issue, seems like it cannot run anything other than a single statement.

I had something like the following:

USE db;
SELECT ...;

If I remove the USE statement, the query runs fine, otherwise I get the 'cannot destructure ...' error.

**Comment by gjsjohnmurray** [comment] 2022-08-13 04:35
See also #651

**Comment by 0xd3bu9** [comment] 2022-08-29 07:37
Did this have a solution? Has anyone successfully removed that warning?
I have problems even with the code
`CREATE TABLE ...`
But the table was created successfully, so what does that mean?

**Comment by incansvl** [comment] 2022-08-29 19:05
> Did this have a solution? Has anyone successfully removed that warning? I have problems even with the code `CREATE TABLE ...` But the table was created successfully, so what does that mean?

I believe it means the code is running correctly but the extension is failing to parse the data being returned by the server correctly. Unfortunately I don't see any responses from the developer here so it seems this extension has probably been abandoned.

**Comment by 0xd3bu9** [comment] 2022-08-30 07:32
Ops, very sad indeed :(. I'll probably remove this extension. I think everyone wants to know if this is working correctly.
The question remains open until the development team updates. A long while more...

**Comment by gjsjohnmurray** [comment] 2022-08-31 10:38
> it seems this extension has probably been abandoned.

It hasn't been abandoned. I am one of the new maintainers, and the original developer is still involved as far as his day job and non-work life permits.

**Comment by gjsjohnmurray** [comment] 2022-09-02 16:05
Fix has been merged.

**Closed by gjsjohnmurray** 2022-09-02 16:05 UTC
Labels: bug, :dollar: Funded on Issuehunt
