### ISSUE TITLE
Extension Host Crash after SQLTools.executeFromInput

### ISSUE THREAD

**Issue by omiba** [mtxr/vscode-sqltools#202] opened 2019-05-02 16:50 UTC
**Describe the bug**
After using a keyboard shortcut to run SQLTools.executeFromInput and having the editor open for a long period of time (30 minutes to an hour) with no activity the Extension Host will crash.

**To Reproduce**
1. Run some queries and leave the SQLTools results open
2. Go work on other things for 30 minutes to an hour
3. Come back and run a query using a keyboard shortcut (this could happen other ways, this is just the way I've seen it multiple times)
4. Watch your CPU spike
5. Wait patiently while the Extension Host crashes

**Expected behavior**
It should have executed the query and displayed the results.

**Screenshots**
https://cl.ly/2ad60fdafc36
https://cl.ly/a235a5973d6a

**Desktop (please complete the following information):**
SQLTools Version [v0.17.18]
VSCode Version: [1.33.1]
Dialect Used: [MSSQL]
OS: [Mac]

**Additional context**
After the crash, i opened the developer tools and looked at the console.  There was an error for SQLTools.  I attached the output to the issue.  It referenced the cpuprofile, so I also attached that.  Not sure if they are helpful or not.

[-1556815266176.log](https://github.com/mtxr/vscode-sqltools/files/3139022/-1556815266176.log)

[exthost-147671.cpuprofile.txt](https://github.com/mtxr/vscode-sqltools/files/3139027/exthost-147671.cpuprofile.txt)

**Comment by mtxr** [comment] 2019-05-03 01:15
They'd totally unexpected. Is it happening all the time with that steps or eventually?

Would you mind sharing other installed extensions you have? 
I might dig deeper to find the root cause of this bug because it's unacceptable

**Comment by omiba** [comment] 2019-05-03 16:21
I've had it happen 5-6 times.  I've just noticed that it seems like it's because of waiting a long time, i'm not 100% sure.

My extensions are;
Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.19.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Name: Laravel Blade Snippets
Id: onecentlin.laravel-blade
Description: Laravel blade snippets and syntax highlight support
Version: 1.19.0
Publisher: Winnie Lin
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade

Name: Material Theme
Id: equinusocio.vsc-material-theme
Description: The most epic theme now for Visual Studio Code
Version: 2.8.2
Publisher: Mattia Astorino
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme


Name: Poor Man's T-SQL Formatter
Id: taoklerks.poor-mans-t-sql-formatter-vscode
Description: A Visual Studio Code extension for Poor Man's T-SQL Formatter
Version: 1.6.10
Publisher: Tao Klerks
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=TaoKlerks.poor-mans-t-sql-formatter-vscode


Name: SQLTools
Id: mtxr.sqltools
Description: Database management done right. Connection explorer, query runner, intellisense, bookmarks, query history. Feel like a database hero!
Version: 0.17.18
Publisher: Matheus Teixeira
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools


Name: vscode-icons
Id: vscode-icons-team.vscode-icons
Description: Icons for Visual Studio Code
Version: 8.6.0
Publisher: VSCode Icons Team
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons

**Comment by mtxr** [comment] 2019-05-05 21:07
@omiba  Thanks! I'll debug it and share my findings here

**Comment by mtxr** [comment] 2019-05-20 06:09
@omiba do you still have this errors?

I tried to reproduce it here, but no success.

**Comment by mtxr** [comment] 2019-05-23 02:50
This error `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` happened before in other projects when we got a memory leak. 

I'll debug registering the footprint tomorrow in my work with a full day using that the extension to see how it goes. But I haven't seen this before. It's weird

**Comment by mtxr** [comment] 2019-05-30 04:00
@omiba any updates?

I've tried again to track it down, still can't reproduce

I'll close this since I believe it's gone. I are already in version v0.19.x, it might have been an isolated issue in that version.

Please, reach me back if you have any updates or the problem persists, we can reopen and try to dig deeper on this

**Closed by mtxr** 2019-05-30 04:00 UTC
Labels: bug
