### ISSUE TITLE
Can't see tables in Connection Explorer - get "Nothing here"

### ISSUE THREAD

**Issue by BrendanSimon** [mtxr/vscode-sqltools#703] opened 2020-09-25 03:39 UTC
**Description**

Connecting to an SQLite database succeeds, however I can't see any of the tables in the CONNECTIONS explorer.

All I see is: ```Nothing here```

I've tried with a full absolute filename, relative file name to workspace directory (with and without the `${workspaceFolder}` variable.

I've installed Node.js/npm.  vscode asked me to install sqlite, which I did.

**Expected behavior**

A list of table names :)

**Screenshots**

![image](https://user-images.githubusercontent.com/472245/94223148-8d29dc80-ff32-11ea-9a5d-e5585cbe0fcf.png)

![image](https://user-images.githubusercontent.com/472245/94223196-a3d03380-ff32-11ea-869c-3e367b5e515d.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.49.2
 - OS: Windows 10 Pro - Microsoft Windows [Version 10.0.19041.508]
 - Driver: SQLite
 - Database version: SQLite 3

**Additional context**

Am using Python 3.7, with SQLAlchemy 1.3.19 for an application.

Can view the tables and data ok with SQLStudio 3.2.1 (though I'm having trouble delete a table and some columns in other tables due to some FK error).  I don't think it is related, but I thought I'd mention it.  I can still see the tables regardless.

**Comment by KerimG** [comment] 2020-09-25 06:42
Got the same issue. 

Same versions as OP.

**Comment by KerimG** [comment] 2020-09-25 06:45
I think the problem is in resolving the SQLite file's location. I went into my workspace's settings and changed the `sqltools.connections` object from 

```json
{
  "sqltools.connections": [
    {
      "previewLimit": 50,
      "driver": "SQLite",
      "name": "Dev",
      "database": "${workspaceFolder:client-backend}/src/db/dev.db.sqlite"
    } 
  ],
}
```

to

```json
{
  "sqltools.connections": [
    {
      "previewLimit": 50,
      "driver": "SQLite",
      "name": "Dev",
      "database": "./src/db/dev.db.sqlite"
    } 
  ],
}
```

and then the connection worked fine.

**Comment by not-so-smart** [comment] 2020-10-16 05:53
@KerimG Thank you!!! This fixed the issue for me too -- I wonder why they use that weird notation if it doesn't work?

**Comment by dynamictulip** [comment] 2021-01-07 13:23
This fixed the issue for me too

**Comment by payen-py** [comment] 2021-01-19 06:37
@KerimG  Thanks a lot, I really solve this issue

**Comment by jamesmyatt** [comment] 2021-01-29 10:13
@KerimG , I can confirm that this workaround works for me, but it's not a permanent solution.

@mtxr, is this easy to fix?

**Comment by jamesmyatt** [comment] 2021-01-29 12:24
I think this is a problem of Windows paths. I've just found an empty `C:\c%3A\__Data\...\data\database.sqlite` file, which I assume was created by sqltools.

**Comment by CyberFoxar** [comment] 2022-09-09 12:06
On windows, using SQLTools `v0.24.0` and SQLTools SQLite `v0.3.0` I can also confirm that this is an issue. 

The new connection wizard wants to use the VSCode variable and it does not work with the tool.

**Comment by gjsjohnmurray** [comment] 2022-09-09 15:29
I have reproduced the issue and prepared a fix. I believe the problem only shows on Windows.

**Closed** 2022-09-11 05:52 UTC
Labels: sqlite, WINDOWS
