### ISSUE TITLE
sqltools not working properly

### ISSUE THREAD

**Issue by kelvenus** [mtxr/vscode-sqltools#666] opened 2020-07-22 11:45 UTC
Issue Type: <b>Bug</b>

Cannot add database or see any options in sqltools settings after installing sqltools extension  

Extension version: 0.22.10
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.16299

![image](https://user-images.githubusercontent.com/3605523/88172565-d124fc00-cbe6-11ea-93c8-9955c9d45f86.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bRaInT00T** [comment] 2020-07-22 15:27
Duplicate of #639

**Closed** 2020-07-23 15:32 UTC

**Comment by mtxr** [comment] 2020-07-24 02:31
Fixed on v0.22.11.
