### ISSUE TITLE
Incorrect data in output table

### ISSUE THREAD

**Issue by vdevelg** [mtxr/vscode-sqltools#1388] opened 2024-10-17 19:04 UTC
# Describe the bug
When executing a certain query, incorrect values are displayed in the output table, and when scrolling, the number of columns in the table is multiplied several times.

# To Reproduce
1. Connect to the database
2. Create an SQL script with the code
```sql
select
    now(),
    now()::date,
    extract (year from now()),
    extract (month from now()),
    extract (day from now()),
    extract (hour from now()),
    extract (minutes from now()),
    extract (second from now());
```
3. Execute the code
4. In the output table, make sure that the values are incorrect
5. Try scrolling through the results table and make sure that the number of columns is increasing!

# Expected behavior
See the date and time parts divided into columns, just like in DBeaver.

# Screenshots
 - from VSCode:
![Screenshot 2024-10-17 230304](https://github.com/user-attachments/assets/e89f95e4-56c8-432e-ab2a-c9a62a50bc75)

 - from DBeaver:
![Screenshot 2024-10-17 230656](https://github.com/user-attachments/assets/ab4c04ca-c67c-46be-a52a-c043ec2d9885)

# Desktop
 - SQLTools Version 0.28.3
 - VS Code Version: 1.94.2
 - OS: Windows 11
 - Driver:
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: PostgreSQL v16.4

# Additional context
I think that's enough. Thank you.

**Comment by gjsjohnmurray** [comment] 2024-10-17 19:24
Is the output correct if you use AS to assign a unique name to each EXTRACT column?

**Comment by vdevelg** [comment] 2024-10-17 19:39
Yes! If you use AS, then it is correct.
Everything seems to break down when there are two or more columns with the same name in the table.

**Comment by gjsjohnmurray** [comment] 2024-10-17 20:05
Duplicate of #1276

**Closed as completed by gjsjohnmurray** 2024-10-17 20:05 UTC
Labels: duplicate
