### ISSUE TITLE
Reuse one results window/tab for all queries

### ISSUE THREAD

**Issue by ryexley** [mtxr/vscode-sqltools#766] opened 2021-02-12 20:25 UTC
**Describe the bug**

Sorry, this is more of a question than a bug report, but the only two options are Feature Request and Bug Report.

What I'd like to know is, is there a setting that will allow me to configure SQLTools such that when I execute a query, that it will reuse the existing results window when I execute a query, rather than opening a whole new window/tab every time I execute a query. If/when I run a bunch of different queries over time, I get so many new tabs opening, and I'd rather just always have the results open in the same tab. Is there a way to do this? I've searched through the issues here and wasn't able to find anything. This seems to have changed since I used this extension last year, as I'm pretty sure it used to do this. Am I missing something? Is there an option for this behavior somewhere?

**To Reproduce**
1. Establish a connection with a database
2. Click to open a new query window
3. Enter in a new sql query, and click "Run on active connection"
4. View query results in new results tab that opens
5. Enter another, different query on a separate line in the same query window, select the query, and again, click "Run on active connection"
6. Observe that another, separate results tab is opened.

**Expected behavior**

When the second, or any subsequent query is executed from the sql query tab, I would prefer that the already-open results tab be reused to display the results of each subsequent executed query.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - SQLTools Version: 0.23.0
 - VSCode Version: 1.53.2
 - OS: MacOS
 - Driver: 
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**
Thanks so much for making and providing such a valuable tool. I do really appreciate all of the hard work that must've gone into such a useful extension to VS Code.

**Comment by gimbo** [comment] 2022-06-23 11:21
Duplicate of #632?

**Comment by gjsjohnmurray** [comment] 2022-07-22 23:46
Closing as a duplicate - thanks @gimbo

**Closed** 2022-07-22 23:46 UTC
Labels: triage
