### ISSUE TITLE
How to run multiple queries at once?

### ISSUE THREAD

**Issue by Artur-nav** [mtxr/vscode-sqltools#551] opened 2020-04-30 11:38 UTC
Hello,

sample queries for Oracle database:
select 1 from dual;
select 'A' from dual;
select sysdate from dual;

After selecting all 3 queries and using Ctrl-E or context menu "Run selected query" it returns:
QUERY
select 1 from dual;
select 'A' from dual;
select sysdate from dual;
MESSAGES
ORA-00933: SQL command not properly ended

So it treats three queries as one. How to "tell" sqltools there are multiple queries?

**Comment by mtxr** [comment] 2020-05-13 07:01
duplicate of #350

**Closed by mtxr** 2020-05-13 07:01 UTC
Labels: triage
