### ISSUE TITLE
Missing Sessions and Multiple Connections features

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#237] opened 2019-05-20 08:34 UTC
As per the changelog and Sessions and Multiple Connections documentation, The sessions/multiple connection management features are in the current v0.19 release, But it's features seem missing - No session files are opened automatically even after changing the relevant setting and the commands are missing from the palette.

**Comment by mtxr** [comment] 2019-05-20 12:28
Yeah, it's not opening because it can't find a root folder. This happens when there is no open folders.

I'll close this since it's caused by #236.

Thanks again @ransagy !

**Comment by mtxr** [comment] 2019-05-20 12:29
I see you have edited this issue. You first comments are true. I'll add that features.

Reopening.

**Closed** 2019-05-20 14:55 UTC
Labels: bug

**Comment by ransagy** [comment] 2019-05-20 16:44
Confirmed, working well now. Thanks!
