### ISSUE TITLE
Open query results in bottom split panel

### ISSUE THREAD

**Issue by niccolomineo** [mtxr/vscode-sqltools#911] opened 2022-06-24 07:05 UTC
At the moment, query results open automatically to the right of the query prompt.

It would be useful to add an option to open the results in a split panel at the bottom of the viewport, in the fashion of many (if not all) the database IDEs.

**Comment by charlesphil** [comment] 2022-07-14 21:19
I believe this is a duplicate of https://github.com/mtxr/vscode-sqltools/issues/280. As far as I can tell, there hasn't been any movement on the issue and I'm also keen to have this feature as well.

**Closed as completed** 2022-08-07 09:00 UTC
Labels: feature request
