### ISSUE TITLE
Do not require database to make a connection 

### ISSUE THREAD

**Issue by Da-Viper** [mtxr/vscode-sqltools#731] opened 2020-11-14 22:43 UTC
**Is your feature request related to a problem? Please describe.*
 I'm always frustrated when i try to make a connection and cannot remmeber the any of the database name on the server 

**Describe the solution you'd like**
Make the database not a required field, if you test connection without the database  it still works.

**Describe alternatives you've considered**
i have tried mssql, apexsql, vscode-database extension all do not require a database name to save the connection. 

i love this extension it is just that stuff that is bugging me as i tend to forget the database name as they tend to be long 

thanks

**Comment by dkbarn** [comment] 2021-01-31 18:55
What I find bizarre is that, at least with the MySQL driver, a database name is required to create the connection, but that connection isn't actually restricted to that database. When I expand the new connection in the CONNECTIONS view, I see every database listed underneath it. This makes requiring the database name not only unnecessary but misleading.

**Comment by gjsjohnmurray** [comment] 2022-07-23 00:17
Duplicate of #727

**Closed** 2023-01-06 15:58 UTC
Labels: duplicate, feature request, mysql

**Comment by gjsjohnmurray** [comment] 2023-01-06 17:34
Workaround is suggested at https://github.com/mtxr/vscode-sqltools/issues/727#issuecomment-1373906407
