### ISSUE TITLE
Linux sqlite, strange behavior

### ISSUE THREAD

**Issue by xenogenesi** [mtxr/vscode-sqltools#511] opened 2020-02-20 22:36 UTC
The "connections" tab does not seem to work properly (I tried the mysql version and it behaves as I expect), sometimes it does not show the tables (it shows the current after creating a new connection), it does not always connect, it does not delete configured connections, probably the refresh does not work. A directory literally called `$ {workspaceFolder}` is created by creating new connections.

**To Reproduce**
Please see the attached video

**Expected behavior**
Normal behavior as with mysql connections

**Screenshots**
https://youtu.be/6ZQv34tzOPo

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.6
 - VSCode Version:1.42.1
 - Driver Used/Version: SQLite
 - OS: Linux/Debian
 - node: v12.14.1
 - sqlite3: sqlite3@4.1.1

**Comment by sciocoder** [comment] 2020-02-21 14:16
the problem is how the database path is saved in the configuration file.

Try replacing $ {workspaceFolder} with dot.

"database": "${workspaceFolder}/Database.db"
to
"database": "./Database.db"

**Comment by xenogenesi** [comment] 2020-02-21 14:39
Thank you @sciocoder ! Now it works great.

I should have thought about it, as far as I'm concerned you can close the issue, but it should replace/resolve the variable automatically I guess, right?

**Comment by sciocoder** [comment] 2020-02-21 14:51
this is just a workaround :-)

**Comment by mtxr** [comment] 2020-06-26 14:38
@xenogenesi `${workspaceFolder}` is a vscode variable. See: https://code.visualstudio.com/docs/editor/variables-reference

We had an issue with the connections on v0.21, but as far as I know is fixed on v0.22. 

@sciocoder thanks for the workaround

**Closed by mtxr** 2020-06-26 14:38 UTC
Labels: triage

**Comment by sciocoder** [comment] 2020-06-26 16:14
@mtxr :blush:
