### ISSUE TITLE
Error using HIve formatting

### ISSUE THREAD

**Issue by Pengchenghua** [mtxr/vscode-sqltools#476] opened 2020-01-08 09:08 UTC
sdt = regexp_replace($ { hiveconf :sdate }, '-', '')

HIVE formats {} to generate Spaces so that errors are reported during HIVE execution

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]    0.21.6
 - VSCode Version: [e.g 1.x.y]   1.41
 - Driver Used/Version: [e.g PostgreSQL 9, Oracle CE, SQLite, MySQL 6, Redshift..]  HIVE
 - OS: [e.g. Windows, Linux, Mac]  win 1064
**Additional context**

sdt = regexp_replace($ { hiveconf :sdate }, '-', '')

HIVE formats {} to generate Spaces so that errors are reported during HIVE execution

**Comment by mtxr** [comment] 2020-02-07 23:53
We currently don't have a support for Hive.

Would you like to work on Hive support?

**Comment by mtxr** [comment] 2020-02-07 23:53
I'll close this since the issue is invalid. We should add hive support first.

**Closed by mtxr** 2020-02-07 23:53 UTC
Labels: triage
