### ISSUE TITLE
The documentation page is missing???

### ISSUE THREAD

**Issue by caesarsamsi** [mtxr/vscode-sqltools#853] opened 2021-08-14 17:50 UTC
I don't understand how 1 million people use this without instructions??? I got it to install, got the driver installed. 

Then what? Where is the management console? Editing, Running, Debugging, Troubleshooting?

The documentation is a big fat "PAGE NOT FOUND".

This extension should at the very least be disabled until the author fixes these glaring issues.

I'm appalled that Microsoft's Visual Studio team allows for this to happen.

Oh and once you get the MySQL driver installed? Good forever fucking luck trying to install the extension. It won't let you!!!

>>

I am at at https://vscode-sqltools.mteixeira.dev/#features

I click Check out all the features and their documentation [here](http://vscode-sqltools.mteixeira.dev/features)

It takes me to [Features](https://vscode-sqltools.mteixeira.dev/features) which is a "Page Not Found"

![Screen Shot 2021-08-14 at 10 45 42 AM](https://user-images.githubusercontent.com/8953119/129455885-31eb4d03-edf3-4241-9a20-33a9ced1377c.png)
![Screen Shot 2021-08-14 at 10 45 22 AM](https://user-images.githubusercontent.com/8953119/129455886-0b1fff21-687b-433a-b9b0-c085d79550ac.png)

**Comment by mtxr** [comment] 2022-08-01 10:24
The page you are referring to is now fixed. Although, I get your point. Documentation is something very important, but in the begging most of the extension install steps were by design added through the extension workflow flow. Not sure if you got to see the extension settings page that got more field types supported even before vscode team added full support to its own JSON schema on vscode settings page itself. That's why most people are able to use it hassle free.

Now we are back to the extension development and the documentation is being improved, but it's a ongoing work, so since the page you were looking for now has a bare minimum index, I'll close this issue.

If you believe it's still not resolved or you have positive feedbacks, please don't hesitate to reopen it. Just please be gentle and polite. We work for free because we believe this will help others, there's no need to be toxic around here

**Closed as completed** 2022-08-01 10:25 UTC
Labels: docs
