### ISSUE TITLE
 Server with many databases crashes the initial listing

### ISSUE THREAD

**Issue by crowley666x** [mtxr/vscode-sqltools#701] opened 2020-09-16 14:59 UTC
**Describe the bug**

If I connect to a server and my user has access to thousands of databases, the initial database listing simply prevents the extension from being used.
After a long time the listing appears, but several actions on the tree take a long time

**Desktop (please complete the following information):**
 - SQLTools 0.23.0
 - VSCode 1.48.2
 - OS: Windows
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...

**Comment by gjsjohnmurray** [comment] 2022-09-05 05:18
Duplicate of #322

**Closed by gjsjohnmurray** 2022-09-05 05:18 UTC
Labels: triage
