### ISSUE TITLE
Detect node runtime complains, but no error is found

### ISSUE THREAD

**Issue by PaulWaldo** [mtxr/vscode-sqltools#1050] opened 2022-12-04 22:18 UTC
**Describe the bug**
When opening VS Code after a reboot, each window that opens displays the modal 
![CleanShot 2022-12-04 at 16 58 03@2x](https://user-images.githubusercontent.com/12105941/205518413-1271c395-40b2-4eb7-ae30-7936b4e67959.png)

There is no apparent error in the terminal window opened, and the SQLTools log does not show anything that looks like an error

```[1670191862364] INFO  (ext): SQLTools is starting
[1670191862367] INFO  (ext): initializing language client...
[1670191862367] INFO  (ext): Detecting node path (if this stalls check Terminal view for the stuck session and kill it)...
    ns: "lc"
[1670191865364] INFO  (ext): Registering client for languages [{"scheme":"sqltools"},{"language":"sql","scheme":"untitled"},{"language":"sql","scheme":"file"},{"language":"sql","scheme":"sqltools"}]
    ns: "lc"
[1670191865367] INFO  (ext): loading plugins...
[1670191865367] INFO  (ext): registering Formatter Plugin.
    plugin: {
      "name": "Formatter Plugin"
    }
[1670191865367] INFO  (ext): registering Connection Manager Plugin.
    plugin: {
      "name": "Connection Manager Plugin"
    }
[1670191865367] INFO  (ext): registering CodeLens Plugin.
    plugin: {
      "name": "CodeLens Plugin",
      "registeredLanguages": []
    }
[1670191865368] INFO  (ext): registering Dependency Manager Plugin.
    plugin: {
      "name": "Dependency Manager Plugin",
      "installingDrivers": []
    }
[1670191865369] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1670191865369] INFO  (ext): registering History Manager Plugin.
    plugin: {
      "name": "History Manager Plugin"
    }
[1670191865370] INFO  (ext): registering Bookmarks Manager Plugin.
    plugin: {
      "name": "Bookmarks Manager Plugin"
    }
[1670191865371] INFO  (ext): SQLTools activation completed. 3010.017866 ms
[1670191865371] INFO  (ext): Formatter Plugin registered!
[1670191865371] INFO  (ext): CodeLens Plugin registered!
[1670191865372] INFO  (ext): Dependency Manager Plugin registered!
[1670191865372] INFO  (ext): Connection Manager Plugin registered!
[1670191865372] INFO  (ext): History Manager Plugin registered!
[1670191865372] INFO  (ext): Bookmarks Manager Plugin registered!
[1670191865820] INFO  (ls): SQLTools Server started!
===============================
Using node runtime?: yes
ExecPath: /usr/local/Cellar/node/18.11.0/bin/node v18.11.0
===============================
[1670191865853] INFO  (ext): registering MySQL/MariaDB Plugin (driver).
    plugin: {
      "extensionId": "mtxr.sqltools-driver-mysql",
      "name": "MySQL/MariaDB Plugin",
      "type": "driver"
    }
[1670191865853] INFO  (ext): registering SQLite Plugin (driver).
    plugin: {
      "extensionId": "mtxr.sqltools-driver-sqlite",
      "name": "SQLite Plugin",
      "type": "driver"
    }
[1670191867222] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1670191867222] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1670191867231] INFO  (ext): LanguageClient ready
    ns: "lc"
[1670191867231] INFO  (ls): Initialized with node version:v18.11.0
[1670191867234] INFO  (ls): REQUEST RECEIVED => ls/RegisterPlugin
[1670191867234] INFO  (ls): request to register plugin: "/Users/paul/.vscode/extensions/mtxr.sqltools-driver-mysql-0.4.1/out/ls/plugin.js"
[1670191867377] INFO  (ls): Driver mysql registered!
    place: "driver-map"
    ns: "ls-context"
[1670191867378] INFO  (ls): Driver mariadb registered!
    place: "driver-map"
    ns: "ls-context"
[1670191867378] INFO  (ls): REQUEST RECEIVED => ls/RegisterPlugin
[1670191867379] INFO  (ls): request to register plugin: "/Users/paul/.vscode/extensions/mtxr.sqltools-driver-sqlite-0.4.1/out/ls/plugin.js"
[1670191867490] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1670191867653] INFO  (ext): MySQL/MariaDB Plugin (driver) registered!
[1670191867545] INFO  (ls): Driver sqlite registered!
    place: "driver-map"
    ns: "ls-context"
[1670191867697] INFO  (ext): SQLite Plugin (driver) registered!
[1670191868697] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1670191868697] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
```

If I reload the VS Code window, everything seems to work, as I am informed `Node runtime auto-detected. Using /usr/local/Cellar/node/18.11.0/bin/node.`

**Expected behavior**
Either no complains on proper operation, or a log describing what the problem is

**Desktop (please complete the following information):**
 - SQLTools Version v0.26.0
 - VS Code Version: 
 - Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
 - OS: macOS Montery 12.6.1
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [X] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by gjsjohnmurray** [comment] 2022-12-05 11:41
Probably a duplicate of #1034

**Closed as completed by gjsjohnmurray** 2022-12-05 11:41 UTC
Labels: duplicate
