### ISSUE TITLE
MariaDB: `Cannot read properties of undefined (reading 'undefined')` returns for every query

### ISSUE THREAD

**Issue by sharpchen** [mtxr/vscode-sqltools#1093] opened 2023-01-18 08:54 UTC
**Describe the bug**
I'm writing very simple queries, these queries are valid and I can get correct results using terminal.
When using sqltools, it returns `Cannot read properties of undefined (reading 'undefined')` for every simple query.

**Screenshots**
![image](https://user-images.githubusercontent.com/77432836/213119903-1e04a5b4-c041-42d0-83ae-8c2d237018ab.png)
![image](https://user-images.githubusercontent.com/77432836/213120119-b6fd9681-95a0-47ff-9ec2-892f1e28571a.png)

**Desktop (please complete the following information):**
 - SQLTools Version [v0.27.1]
 - VS Code Version: [1.74.3]
 - OS: [Windows]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [10.9.2-MariaDB]

**Comment by sharpchen** [comment] 2023-01-19 07:42
Found a solution:
Run `USE <database>` first, then run the query, it works.

**But really do I have to do this, or it's just a bug?**

**Comment by mtxr** [comment] 2023-02-12 03:30
do you have a database set on you settings.json file?

**Comment by sharpchen** [comment] 2023-02-15 12:28
I have set a default database to connect. To be clear, this issue is about it cannot execute query together with `use <database>`. I'm not sure whether I have clearly expressed myself, feel free to comment if you don't understand me.

**Comment by gjsjohnmurray** [comment] 2023-04-27 15:11
Duplicate of #1131

**Closed as completed by gjsjohnmurray** 2023-04-27 15:11 UTC
Labels: duplicate, mysql
