### ISSUE TITLE
add-driver script for supporting new driver fails

### ISSUE THREAD

**Issue by juanmonsa** [mtxr/vscode-sqltools#573] opened 2020-05-22 01:33 UTC
The script fails because a missing file docs/src/components/checkLocation.ts, whch was deleted in a previous commit

**Comment by BNMeier** [comment] 2020-05-25 13:59
This was reported in issue #557. No update on this as of yet.

**Comment by mtxr** [comment] 2020-05-25 16:35
Duplicate of #557

**Closed by mtxr** 2020-05-25 16:35 UTC
Labels: triage
