### ISSUE TITLE
Add new connection icon invisible

### ISSUE THREAD

**Issue by violet-fish** [mtxr/vscode-sqltools#1223] opened 2023-10-11 17:36 UTC
**Describe the bug**
The "Add new connection" button is invisible. 

**To Reproduce**
1. Go to SQLTools tab
2. Add new connection button does not show

**Expected behavior**
Visible "Add new connection" button

**Screenshots**
![Screenshot 2023-10-11 112757](https://github.com/mtxr/vscode-sqltools/assets/444722/0e5bf31e-4338-4a62-a933-e98807502ee7)

**Desktop (please complete the following information):**
 - SQLTools Version v0.28.0
 - VS Code Version: 1.83.0
 - OS: Windows 11 22H2 22621.2428
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL 5.7

**Additional context**
I have tried updating plugins and vscode, but the plugins and editor are already up to date

**Comment by gjsjohnmurray** [comment] 2023-10-11 17:51
This is caused by a VS Code change in 1.83.0 which will be fixed in the upcoming 1.83.1 release, probably later today.

**Closed as completed by gjsjohnmurray** 2023-10-11 17:51 UTC
Labels: triage

**Comment by violet-fish** [comment] 2023-10-11 17:58
@gjsjohnmurray Thanks, I'm glad to hear it's going to be fixed soon.

I thought I was going crazy when I looked up guides that mentioned the add connection button but I didn't see it. I'm glad I decided to hover over where I thought it should be and noticed it was just invisible.
