### ISSUE TITLE
Impossible delete database from explorer

### ISSUE THREAD

**Issue by Gianluks90** [mtxr/vscode-sqltools#130] opened 2019-02-12 23:35 UTC
Hi! I'm learning to use databases and your extension, however I have a problem: I can not delete a database created by mistake from the explorer. This is a bug?

**Comment by mtxr** [comment] 2019-02-12 23:44
Hi @Gianluks90! No, it's not a bug. We currently doesn't have a option to remove the database via UI.
There's a issue for it, issue #64, but for now you can remove using vscode default settings editor.

Open the `Command Palette` and type  `settings`. It the `Preferences: Open Settings (JSON)`.

When the file opens, search for `sqltools.connections`, delete the lines of the connection created by mistake and it will disappear from the explorer.

![image](https://user-images.githubusercontent.com/707561/52675669-ae30eb80-2f0e-11e9-83f2-b70462a7f9ba.png)

Thank you for submitting this issue. I'll close it in favor of #64.

Could you please give a :+1: for that feature? Makes easier to prioritize here.

Thanks!

**Closed by mtxr** 2019-02-12 23:44 UTC
Labels: bug

**Comment by zaksenards** [comment] 2024-12-18 22:45
Same problem here
![Captura de tela 2024-12-18 194417](https://github.com/user-attachments/assets/74d21358-ef33-4c87-9357-cd465b08c356)
